### ISSUE TITLE
Rtm_Json_Creatorのページでファイルの出力ができない

### ISSUE THREAD

**Issue by waya0125** [akikawaken/akikawaken.github.io#1]
### 現象

[Rtm_Json_Creator](https://aikawaken.github.io/RJC/Json/Create/train.html)でJSONを作成したところ、空のJSONファイルが出力されました。

### 期待される動作

フォームに入力した情報をもとに、RTMの求める形式のJSONが生成され、出力される状態が正常だと思われます。

### 原因

変数の定義は
https://github.com/akikawaken/akikawaken.github.io/blob/c707bd26f9d373614ce75de54a08c7a47e66e903/RJC/Json/Create/train.html#L344
の通り、`maxSpeed1`と定義されています。  
しかし、使用している箇所では
https://github.com/akikawaken/akikawaken.github.io/blob/c707bd26f9d373614ce75de54a08c7a47e66e903/RJC/Json/Create/train.html#L349-L351
の通り`maxSpeed`となっています。

### 修正方法

`maxSpeed`となっている場所を、`maxSpeed1`に変更する必要があります。  
上記の使用箇所を、
```JavaScript
if (maxSpeed5 !== "") {
    output += ' "maxSpeed": [' + maxSpeed1 + ',' + maxSpeed2 + ',' + maxSpeed3 + ',' + maxSpeed4 + ',' + maxSpeed5 + ' \n';
}
```
とすると正常に動作するかと思います。

**Comment by akikawaken** [comment]
waya0125 さん、ご指摘ありがとうございます。
コミット: [cbfbf5e](https://github.com/akikawaken/akikawaken.github.io/commit/cbfbf5ee3ba1d824c1d524b94c7ed428b7d2c95a) にてその問題を修正しました。

また、同時に`output += ' "maxSpeed": [' + maxSpeed1 + ',' + maxSpeed2 + ',' + maxSpeed3 + ',' + maxSpeed4 + ',' + maxSpeed5 + ' \n';`に`],`の部分が抜け落ちていた問題も修正しました。
